#Explicação deste sistema:
#Bom este sistema será um sistema de bases que o administrador que tiver a permissão, setara cada base em locais que desejar no mapa!
#O sistema irá depender da api do plugin yclans, vault, holographicdisplays e worldguard.
#O sistema irá possuir sistema de alarme ao invadir e seguranças no Cofre.
#Terá um comando para desativar temporariamente as insões de bases, por apenas admistradores, para caso ter um campeonato e as pessoas se aproveitar pra invadir bases dos clans que estão no camp.
#Tem mensagens de debug a ser exibidas, com o tempo do desenvolvimento vou pedindo pra por, quando formos testar e tal, talvez eu esqueci algumas.

Comandos_ajuda: #voxybases.admin permissao para ver a mensagem de ajuda, o unico comando sem permissao é o /base
- ''
- '&6Voxy Bases'
- '&e/voxybases criarbase (nome da regiao' #comando para criar uma base #tipo upbases, /bases criarbase <nome da regiao q foi definida>
- '&e/voxybases setarcofre (nome da base)' #comando para setar um cofre
- '&e/voxybases removercofre (nome da base)' #comando para remover um cofre
- '&e/voxybases setarportao (nome da base) (nome do portao)' #vai ter animação, tenho que explicar in-game, dará pra criar varios portões na base, mas hackeando 1 todos abrirão.
- '&e/voxybases deletarportao (nome da base) (nome do portao)' #comando para remover um portao
- '&e/voxybases reload' #comando de reload dos arquivos
- '&e/base' #comando utilizado para o jogador ir para sua base, vai abrir um menu
- ''

Opcoes:
  Desfazer_clan: true #caso o clan for desfeito, a base será largada, o proprio plugin de clan tem um sistema de inatividade e taus, além disso os itens dos cofres ficam nas bases quando elas sao abandonadas, para por exemplo um clan pegar a base e os itens deixados
  Roubar_Base: true
  Precisa_Hackear: true

Portao: #quando o servidor reiniciar, todos os portoes das bases irao ser fechados
  Item_hacker:
    material: 'stone:0' #usando como exemplo a pedra, todas as pedras, mesmo sendo renomeadas, com nbt, não importa, irão ser utilizadas como o item de hack
    nome: '&aItem para hackear'
    lore:
    - ''
    - '&cHackeando tudo!'
    - ''
  Item_parar_hacker:
    material: 'dirt:0'
    nome: '&aInterromper Hackeamento'
    lore:
    - ''
    - '&Para qualquer hackeamento!'
    - ''
  Mensagem_ja_invadindo: '&cSeu clã já está invandindo uma base, aguarde a invasão terminar para invadir outra base!' #mensagem enviada caso o jogador tente hackear um portao enquanto o seu clan esteja invadindo uma base no momento
  Ativar_invadindo_sem_jogadores_on: false #ativar a funcao a baixo
  Mensagem_invadindo_sem_jogadores_on: '&cNão é possivel invadir está base, pois não há jogadores online do clan rival para defender.' #caso nao tiver nenhum jogador online do clan rival, não será possivel invadir
  Tempo_hackear_portao: 60 #em segundos
  ActionBar_hackeando_portao_segundos: '&cHackeando o portão, aguarde mais &f{tempo} &csegundos.'
  ActionBar_portao_hackeado: '&aPortão hackeado com sucesso, dentro de 15 minutos ele fechará.'
  Tempo_fechar_portao: 15 #em minutos (tempo para o portao fechar apos ser hackeado
  Mensagem_tempo_portao:
    01: #este é o numero da açao, seguindo em forma crescente, podendo ter até o numero 99
      Tempo: 5:00 #tempo restante, formato: minutos:segundos
      Som_tempo: '' #som executado, deixe vazio para nao envia nenhum
      Mensagem_chat: '&cO portão irá se fechar em &f5 &cminutos.'
    02:
      Tempo: 3:00
      Som_tempo: ''
      Mensagem_chat: '&cO portão irá se fechar em &f3 &cminutos.'
    03:
      Tempo: 1:00
      Som_tempo: ''
      Mensagem_chat: '&cO portão irá se fechar em &f1 &cminuto.'
    04:
      Tempo: 0:30
      Som_tempo: ''
      Mensagem_chat: '&cO portão irá se fechar em &f30 &csegundos.'
    05:
      Tempo: 0:10
      Som_tempo: ''
      Mensagem_chat: '&cO portão irá se fechar em &f10 &csegundos.'
  Som_fechando: ''
  Portao_fechando_title:
  - '&cAtenção!'
  - '&fO portão está &cfechando&f.'
  Som_abrindo: ''
  Portao_abrindo_title:
  - '&cAtenção!'
  - '&fO portão está &aabrindo&f.'

Centro_de_controle: #configuração do item de controle da base, vou usar de exemplo um beacon
  Item_hacker:
    material: 'stone:0' #usando como exemplo a pedra, todas as pedras, mesmo sendo renomeadas, com nbt, não importa, irão ser utilizadas como o item de hack
    nome: '&aItem para hackear'
    lore:
    - ''
    - '&cHackeando tudo!'
    - ''
  Item_parar_hacker:
    material: 'dirt:0'
    nome: '&aInterromper Hackeamento'
    lore:
    - ''
    - '&Para qualquer hackeamento!'
    - ''
  Cofre_item: 'BEACON' #Este será o item que será colocado no chão apos setar o Cofre da base.
  Mensagem_erro_colocar_centro: '&cVocê não pode colocar o Centro da Base fora de seu território.' #mensagem enviada caso o staff tente colocar o centro de comando fora da regiao
  Mensagem_possui_base: '&cSeu clã já possui uma base dominada.' #essa mensagem será exibida caso o jogador tente dominar roubar uma base tendo uma ja
  Aliados: true #se true, vai permitir aliados entrar na base sem disparar o alarme, mas não irá permitir que aliados tentem qualquer tipo de invasao, se false, os aliados poderão entrar e roubar tudo, disparando o alarme e etc, como jogadores normais
  Dropar_pegar: false #se true, os jogadores poderão dropar itens e pergar itens do chao com menu de controle aberto, se false, ira bloquear. (anti-dupe)
  Lider_upgrades: true #Se true, apenas o lider pode comprar upgrades no menu de controle
  Tempo_Parar_Invasão: 180 #em segundos
  Sistema_upgrade:
  #ao evoluir a segurança, irá demorar mais tempo para invasores hackarem o centro de controle e o portao
    Segurança:
      nivel_1: #o numero 1 como padrão ja vem liberado.
        tempo_hackear: 60 #tempo em segundos para ser hackeado
      nivel_2:
        tempo_hackear: 120 #segundos (faz a formatação, acima de 60 '1 minuto e 20 segundos')
        custo_upgrade: 25.000 #o custo não é do dinheiro do jogador, mas sim o do clan, utilizado o sistema do yclans: https://github.com/yChusy/yclans-api Getting clan money - double money = clan.getMoney();
      nivel_3:
        tempo_hackear: 180 #segundos
        custo_upgrade: 50.000
      nivel_4:
        tempo_hackear: 240 #segundos
        custo_upgrade: 75.000
      nivel_5:
        tempo_hackear: 300 #segundos
        custo_upgrade: 100.000
  #ao evoluir o cofre, irá liberar um armazem, duvidas esplico em game.
    Armazens_cofre:
      nivel_2:
        custo_upgrade: 50.000 #o custo não é do dinheiro do jogador, mas sim o do clan, utilizado o sistema do yclans: https://github.com/yChusy/yclans-api Getting clan money - double money = clan.getMoney();
      nivel_3:
        custo_upgrade: 75.000
      nivel_4:
        custo_upgrade: 100.000
      nivel_5:
        custo_upgrade: 150.000
  #Obs: quando o Cofre for hackeado, a segurança e a protecao irao voltar para o nivel 1, sendo necessario evoluir novamente, o cofre continuara no nivel que estava

Holograma_Cofre_altura: 3 #altura do holograma
Holograma_Cofre: #Este holograma ficará acima do Cofre da base.
- '&e&l&nCofre da Base'
- ''
- 'Base do Clã: {clan_colored_tag}'
- 'Nível de segurança: {nivel_segurança}' #1,2,3 de acordo com a quantidade de segurança desbloqueada no menu que vou mostrar no sv voxymc.net, fiz exemplos la.
- ''

Holograma_Cofre_Hackeando:
- '&e&l&nCofre da Base'
- ''
- 'Hackeando: {tempo_segurança_animação}' # > https://prnt.sc/1ufzhg2 < print demonstrativa, de acordo o tempo for passando a barra vai ficando verde, quadradinho por quadradinho, mas n quero ela de inicio cinza, e sim vermelha, caso o jogador se mover(andar), o tempo voltará ao inicio.
- 'Tempo estimado: {tempo_segurança}'
- ''

Holograma_Cofre_Hackeado:
- '&e&l&nCofre da Base'
- ''
- '&7Status: &aHackeado com sucesso!'
- ''
- '&7Tempo para o sistema ser restaurado:'
- '&c{time}'
- ''

Holograma_Cofre_Tomado:
- '&e&l&nCofre da Base'
- ''
- 'Tomado por: {clan_colored_tag}'
- ''

Holograma_Cofre_Sem_clan:
- '&c&lBase de Clan'
- ''
- '&7Clan: &cNenhum'
- ''
- '&aClique aqui para dominá-la!'
- ''

Tempo_holograma: 10 #em segundos, apos o tempo ser vencido, vai voltar pro holograma inicial @Holograma_Cofre, e quando o hackeamento é interrompido a tempo, não é perdido os niveis de segurança!
Holograma_Cofre_parar_Hackeamento:
- '&e&l&nCofre Base'
- ''
- 'Hackeando: Hackeamento interrompido!'
- ''

#Alarme base
Alarm_Base: #Uma coisa importante, caso um clan estiver invadindo uma base, e outro jogador do mesmo clan que estiver invadindo tentar invadir outra base não será permitido, emite uma mensagem empurrando ele para fora. (pode até teleportar para um ponto setado, vamos discutir.)
  #info: Caso um clã estiver atacando uma base, e um jogador sem clã entrar junto, não irá mudar nada, vai aparecer apenas que o clan ta invadindo, isso serve para caso um jogador estiver invadindo, permanecerá o jogador invadindo.
  Som_Alarme: true #não quero um som configuravel, tenho um plugin de base parecido pra você usar como base, vai te ajudar muito, quero que executa o som que ele faz quando a base é invadida, nos conversa dps a respeito.
  ActionBar:
    Delay: 30 #será um delay em ticks, para a mensagem passar para a de baixo e de baixo para cima, assim sucessivamente. é tipo uma animação de cores, se existir outra maneira de fazer, sinta-se a vontade.
    Vitimas:
      Clan: #exibir a tag (colorida) do clan que está atacando.
        Actionbar_1: '&eA base está sendo atacada pelo clan: {clan_colored_tag}'
        Actionbar_2: '&cA base está sendo atacada pelo clan: {clan_colored_tag}'
      Jogador: #pode entrar 10 jogadores, mas vai exibir o primeiro jogador que entrar na regiao.
        Actionbar_1: '&eA base está sendo atacada pelo clan: {jogador}'
        Actionbar_2: '&cA base está sendo atacada pelo clan: {jogador}'
    Atacantes: #exibir a tag (colorida) do clan que o clan atacante está atacando. (bem confuso de entender oque eu quis dizer.)
      Actionbar_1: '&eVocê está atacando a base do clan: {clan_colored_tag}'
      Actionbar_2: '&cVocê está atacando a base do clan: {clan_colored_tag}'
  Title:
    Delay: 3 #delay em segundos que permanecerá na tela. (enviado so uma vez, na invasão.)
    Vitimas:
      Clan: #exibir a tag (colorida) do clan que está atacando.
        title:
        - '&c&lINVASÃO DA BASE'
        - '&e&lClan invadindo: {clan_colored_tag}'
      Jogador: #pode entrar 10 jogadores, mas vai exibir o primeiro jogador que entrar na regiao.
        title:
        - '&c&lINVASÃO DA BASE'
        - '&e&lJogador invadindo: {clan_colored_tag}'
    Atacantes: #exibir a tag (colorida) do clan que o clan atacante está atacando. (bem confuso de entender oque eu quis dizer.)
      title:
      - '&c&lINVASÃO DA BASE'
      - '&e&lInvadindo base do clan: {clan_colored_tag}'